apiVersion: v1
kind: Pod
metadata:
  name: myt-hello-nginx
  labels:
    app: myt-hello-nginx
    type: front-end
spec:
  containers:
  - name: myt-hello-nginx-container
    image: ahmadshaugi81/hello-nginx