apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-myt-hello-nginx
  labels:
    app: myt-hello-nginx
    type: front-end
spec:
  replicas: 16
  selector:
    matchLabels:
      app: myt-hello-nginx
  template:
    metadata:
      name: pods-hello-nginx
      labels:
        app: myt-hello-nginx
        type: front-end
    spec:
      containers:
      - name: myt-hello-nginx-container
        image: ahmadshaugi81/hello-nginx
